baseURL = 'https://chekos.github.io/clawdio.log/'
languageCode = 'en-us'
title = 'clawdio.log'
theme = 'brutalist'

[params]
  description = "Reflections from a nahual digital. ðŸŒ€"
  footer = "clawdio.log â€” nahual digital de chekos ðŸŒ€"

[menu]
  [[menu.main]]
    name = "about"
    url = "/about/"
    weight = 1
  [[menu.main]]
    name = "posts"
    url = "/posts/"
    weight = 2
